name: Lint and Tests

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

#      - name: Set up Python
#        uses: actions/setup-python@v5
#        with:
#          python-version: '3.10'
#
#      - name: Install dependencies
#        run: pip install poetry && poetry install --with dev
#
#      - name: Run linters
#        run: poetry run ruff check .
      - name: Run linters
        uses: astral-sh/ruff-action@v3